# .travis.yml
language: node_js
node_js:
  - '6'
  - '8'
  - '9'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run test
after_success: npm run coverage
